# Generated by Django 4.2.1 on 2024-06-09 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_marca_id_alter_product_id'),
        ('app', '0002_alter_product_image'),
    ]

    operations = [
    ]
